name: OPA Test
on: [push]
jobs:
  opa:
    name: opa test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: test
      uses: "petroprotsakh/opa-test-action@v2.1"